config/routes.rb
#in routes we put all our URL's here

Rails.application.routes.draw do
  # Rails is an MVC framework. Model, view, control
  #Model - ruby version of a database table
  #view - HTML / ERB code
  #control - pulls a model/models from database and sets instance variables
  #for our view
  root 'posts#index' #index means all of it. equivalent to SELECT * FROM posts. 
                     #goes from post controller to index method
                                          #adding an alias, which is adding a path prefix so that we can create a link
  get 'posts/:id', to: 'posts#show', as: 'post_show' #:id is called a dynamic place holder. 
                                    #so we oculd put localhost:3000/posts/6 and post six will show up on web browser
  get 'post', to: 'posts#new'

  get 'edit_post/:id', to: 'posts#edit', as: 'edit_post'

  post 'posts', to: 'posts#create'

  patch 'post', to: 'posts#update'

  delete 'posts', to: 'posts#destroy'


end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
#this wraps our post table 

class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # GET HTTP VERB
    # get all posts out of the database
    @posts = Post.all #creating an instance variables so view can have access to it from the controller 
    # .all method ALWAYS returns an array 
  end

  def show
    # GET HTTP VERB
    # gets a single post from the database
    @post = Post.find(params[:id]) #find(params[:id]) will return the post with the id you want
  end

  def new
    # GET HTTP VERB
    # shows the form to create a new post
    @post = Post.new
  end

  def create
    # POST HTTP VERB
    # creates a new post record in our database
    
    @post = Post.new(post_params) #calling post_params method
    if @post.save 
      #calling .save on an instance variable to save that to our database
      #if we successfully save a post record
      #we dont need a view here, we will redirect the user to show, or wherever
      # redirect_to "/posts/#{@post.id}"  this is hard code below is rails ruby way 
      redirect_to post_show_path(@post)
    else
      # if it fials to save in the database for some reason
      render :new # show user there was an error and allow them to retry
    end
  end

  def edit
    # GET HTTP VERB 
    # shows the same form that new does, but prefills it with the post data
    # need to grab a post with id out of the database, just like show method
    @post = Post.find(params[:id]) # SQL words: SELECT * FROM posts where post.id = params[:id]
  end

  def update 
    # PUT/PATCH HTTP VERB
    # updating the post record values
    # need to find the format(id) in the database, and update
    @post = Post.find(params[:format])
    if @post.update(post_params)
      redirect_to post_show_path(@post)
    else
      render :edit
    end
  end

  def destroy
    # DELETE HTTP VERB
    # deletes a single post record from our database
    @post = Post.find(params[:format])
    @post.destroy 
    redirect_to root_path
  end

  private #this is where we allow or disallow data from our posts to enter our database. 
    def post_params
      params.require(:post).permit(:title, :author, :body) #allowing only title author and body to be put into database. this is a strong parameter.PARAMS IS ALWAYS A HASH( KEY VALUE PAIR)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<!--generates a html form for that specific post -->
<h1>
  Editing: <%= @post.title %>
</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>
  
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

<!--rails is smart enough to know that these fields already have values, and output them.-->

<%= link_to 'Back', post_show_path(@post) %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<!--creating a loop for Post.all and making an li for each item inside the array, and showing it to the user-->
<ul>
  <% @posts.each do |post| %>
    <li> <%= link_to post.title, post_show_path(post) %> </li>
  <% end %>
</ul>

<%= link_to 'New Post', post_path %>


  

app/views/posts/new.html.erb
<!-- this is where form will go to create a new post-->

<h1>Create a New Post</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %> <!-- creates a submit button for us -->
<% end %>

<%= link_to 'All Posts', root_path %>     <!-- <a href='/'>All Posts</a>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1> <!-- this is going to pull up the title of the specific post id -->
<i> Author: <%= @post.author %> </i>
<i> Posted At: <%@post.created_at %> </i>
<p> <%= @post.body %> </p>

<%= link_to 'Edit', edit_post_path(@post) %>
                                                            
<%= link_to 'Delete', posts_path(@post), method: :delete, data: {confirm: 'Really Delete?'} %>

<%= link_to 'All Posts', root_path %>